# Generated by Django 3.2.6 on 2021-08-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO', models.IntegerField()),
                ('SAMPLE_ID', models.IntegerField()),
                ('code', models.CharField(max_length=30)),
                ('DB', models.CharField(max_length=30)),
                ('Foodname1', models.CharField(max_length=20)),
                ('One_timesupply', models.FloatField()),
                ('energy', models.FloatField()),
                ('Protein', models.FloatField()),
                ('Fat', models.FloatField()),
                ('Carbohydrate', models.FloatField()),
                ('Totalsugars', models.FloatField()),
                ('Foodname2', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='Carbohydrate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='Fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='One_timesupply',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='Protein',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='energy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='sugars',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='total_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('total_One_timesupply', models.FloatField()),
                ('total_Carbohydrate', models.FloatField()),
                ('total_Protein', models.FloatField()),
                ('total_Fat', models.FloatField()),
                ('total_sugars', models.FloatField()),
                ('total_energy', models.FloatField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
