# Generated by Django 3.2.6 on 2021-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_nutritionfacts_foodname1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_information',
            name='total_Carbohydrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_information',
            name='total_Fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_information',
            name='total_One_timesupply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_information',
            name='total_Protein',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_information',
            name='total_energy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_information',
            name='total_sugars',
            field=models.FloatField(null=True),
        ),
    ]
